first
Pavel-go-basik/go-testify pull request #1
Opened 2024-03-25 23:14 UTC by Pavel-go-basik

2024-03-25 23:22 UTC, Pavel-go-basik commented
Наверное стоит использовать assert.NotEmpty(t, responseRecorder.Body) вместо assert.NotNil(t, responseRecorder.Body).
В ТЗ не сказано, но возможно при проверка responseRecorder.Code использовать пакет require?

2024-03-25 23:28 UTC, dirtymew commented
> Наверное стоит использовать assert.NotEmpty(t, responseRecorder.Body), вместо assert.NotNil(t, responseRecorder.Body)? В ТЗ не сказано, но возможно при проверка responseRecorder.Code использовать пакет require?

<img width="802" alt="image" src="https://github.com/Pavel-go-basik/go-testify/assets/8639955/3318a3a0-1318-4038-9498-b32f41b9c754">

2024-03-25 23:31 UTC, Pavel-go-basik commented
Это рекомендации, а не ТЗ. Я с ними ознакомился после отправки кода на ревью.
Как насчет assert.Len(t, list, totalCount) ?

2024-03-25 23:33 UTC, dirtymew requested changes
Привет Павел

хорошая работа - тест кейсы верные

нужно доработать немного см PR

2024-03-25 23:33 UTC, dirtymew commented on precode.go
> +func TestMainHandlerWhenOk(t *testing.T) {
код и тесты в go в разных файлах пишутся - в теории было про это

2024-03-25 23:33 UTC, dirtymew commented on precode.go
> +	assert.Equal(t, responseRecorder.Code, http.StatusOK)
тут лучше require

2024-03-25 23:33 UTC, dirtymew commented on precode.go
> +	assert.Equal(t, responseRecorder.Code, http.StatusOK)
логически разные блоки кода пустыми строками стоит отделять - так читаемость улучшьгается

2024-03-25 23:33 UTC, dirtymew commented on precode.go
> +	assert.NotNil(t, responseRecorder.Body)
тут notEmpty лучше - пустая строка это не nil

2024-03-25 23:33 UTC, dirtymew commented on precode.go
> +	expected := `wrong city value`
лишняя переменная можно просто - `assert.Equal(t, responseRecorder.Body.String(), "wrong city value")` читает нормально

2024-03-25 23:33 UTC, dirtymew commented on precode.go
> +	body := responseRecorder.Body.String()
тут тоже код ответа нужно проверить

2024-03-25 23:34 UTC, Pavel-go-basik commented on precode.go
> +	assert.NotNil(t, responseRecorder.Body)
Разве assert.NotNil(t, responseRecorder.Body) не тоже самое что assert.NotEmpty(t, responseRecorder.Body.String()) ?

2024-03-25 23:35 UTC, Pavel-go-basik commented on precode.go
> +	body := responseRecorder.Body.String()
Все строго по ТЗ )

2024-03-25 23:41 UTC, Pavel-go-basik commented on precode.go
> +func TestMainHandlerWhenOk(t *testing.T) {
Ну видимо фаил _test.go скрывается. Поэтому дали такой прекод... возможно

2024-03-25 23:42 UTC, Pavel-go-basik commented on precode.go
> +	assert.Equal(t, responseRecorder.Code, http.StatusOK)
ок

2024-03-25 23:47 UTC, Pavel-go-basik commented
Вроде все поправил, кроме выделения тестов в отдельный фиал

2024-03-25 23:54 UTC, dirtymew commented
> Вроде все поправил, кроме выделения тестов в отдельный файл

это обаятельно надо сделать иначе тесты не запустится

проверь запуск из go test ./...

2024-03-25 23:56 UTC, dirtymew commented on precode.go
> +func TestMainHandlerWhenOk(t *testing.T) {
нейминг тестов не такой go

если код который мы тестируем в main.go

то файл с тестами должен назваться main_test.go

2024-03-25 23:59 UTC, Pavel-go-basik commented
Сделал

2024-03-26 00:03 UTC, dirtymew requested changes

2024-03-26 00:03 UTC, dirtymew commented on precode.go
> +	"github.com/stretchr/testify/require"
импорты все в куче - используй go imports для форматирования

2024-03-26 00:03 UTC, dirtymew commented on precode.go
> +	body := responseRecorder.Body.String()
это не ТЗ а домашнее задание - и можно и нужно на нем учиться и выходить за его рамки - так быстрее будет процесс проходить, не возможно все описать в задании. Предполагается что в каждом новом задании нужно применять опыт из предыдущих в том числе. 

Я тут рекомендую проверить код ответа - если сможешь обосновать почему это не нужно, то ок приму.

2024-03-26 00:06 UTC, Pavel-go-basik commented
https://github.com/Pavel-go-basik/go-testify/pull/1#discussion_r1538384636
Так я сделал чуть ниже
func TestMainHandlerWhenCountMoreThanTotal(t *testing.T) {
	totalCount := 4
	req := httptest.NewRequest("GET", "/cafe?count=7&city=moscow", nil)

	responseRecorder := httptest.NewRecorder()
	handler := http.HandlerFunc(mainHandle)
	handler.ServeHTTP(responseRecorder, req)

	body := responseRecorder.Body.String()
	list := strings.Split(body, ",")

	**require.Equal(t, http.StatusOK, responseRecorder.Code)**
	assert.Len(t, list, totalCount)
}

2024-03-26 00:15 UTC, dirtymew commented on precode.go
> +	assert.NotNil(t, responseRecorder.Body)
если NotEmpty то  assert.NotEmpty(t, responseRecorder.Body) 

NotEmpty проверит и на nil и на пустое значение типа

а если еще глубже заглянуть в функцию String() то там вообще интересно 
```
func (b *Buffer) String() string {
	if b == nil {
		// Special case, useful in debugging.
		return "<nil>"
	}
	return string(b.buf[b.off:])
}
```

те если Body будет nil то Body.String() - вернет не пустую строку а "<nil>""  ....

2024-03-26 00:17 UTC, Pavel-go-basik commented
Мы ведь тесты пишем для проверки выполнения определенных сценариев. у нас нет сценария для w.WriteHeader(http.StatusBadRequest) при count > cafeList[city], по колличеству естественно, поэтому и проверять смысла нет.

2024-03-26 00:21 UTC, Pavel-go-basik commented on precode.go
> +	"github.com/stretchr/testify/require"
устранил

2024-03-26 00:22 UTC, Pavel-go-basik commented
Код-ревью в онлайн формате максимально круто! ) спасибо!

2024-03-26 00:26 UTC, dirtymew commented
> Мы ведь тесты пишем для проверки выполнения определенных сценариев. у нас нет сценария для w.WriteHeader(http.StatusBadRequest) при count > cafeList[city], по колличеству естественно, поэтому и проверять смысла нет.

не это не так. тесты пишутся и как на предполагаемое поведение так и могут проверять и не предполагаемое. но к данному случаю это не относится тут  мы просто далаем вызов и если нам придет не код 200 то и нет смысла вообше проверять есть ли там данные и какие - падаем и все, 

также тесты не должны знать ничего про то как код который они тестируют работает - те мы в тесте подаем входные параметры и потом сверяем с результатом - тут конечно не все так просто и когда придется работать с моками то все-таки что-то знать про код требуется - но идеологически тесты должны так быть устроены.

2024-03-26 00:28 UTC, Pavel-go-basik commented
Тогда код ответа всегда нужно проверять, а вдруг...

2024-03-26 00:30 UTC, dirtymew requested changes
Все вроде теперь ок

вопросы все закрыты - отправляй на ревью повторно

2024-03-26 00:33 UTC, dirtymew commented
> Тогда код ответа всегда нужно проверять, а вдруг...

тут как с ошибкой в go - всегда ее проверяем...

в целом проверить не проблема - но есть и другая сторона этого - лишние проверки того что и так должно работать или покрывается другими тестами - и вот это как раз аргумент )

2024-03-26 00:33 UTC, Pavel-go-basik commented
Оу, я думал этот примем. Я изменения прям в веб версии гита вносил. 
Сейчас попробую.

2024-03-26 00:33 UTC, merged

2024-03-26 00:34 UTC, dirtymew commented
> Оу, я думал этот примем. Я изменения прям в веб версии гита вносил. Сейчас попробую.

не это и отправляй
все в одном PR